spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 5MB # 单个文件大小
      max-request-size: 5MB  # 设置总上传的数据大小
      enabled: true #开启

fdfs:
  so-timeout: 1501 #超时时间
  connect-timeout: 601 #连接超时时间
  thumb-image: #缩略图
    width: 100
    height: 100
  tracker-list: #tracker地址
    - 182.254.148.75:22122

comment.avatar: /images/avatar.png

server:
  tomcat:
    connection-timeout: 20000
    max-http-form-post-size: 5MB
