spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://182.254.148.75:3306/blog?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 981333949zyc.

logging:
  level:
    root: info
    com.curtis.curtisblog: debug
  file:
    name: log/blog-dev.log

mybatis:
  type-aliases-package: com.curtis.curtisblog.entity

pagehelper:                #分页插件
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: