spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ENC(oEZTCJLkw8uOW2w6nYGfOmjRXEzhAB5wHkdvc5HFUsnKHhS8QEmE/dJGmsfNI/ks0KzvQqibGrRhKgm6SyZPSE97arU84Yxzcwge5se4jYTjFuv0wsZZNqmPiLgZYvBJhYpC3nUbAoU=)
    username: ENC(zjJY6otpXddt401Yup3EsA==)
    password: ENC(msMC9Kij/I7X+jp1ib6s9tiPKnmeC4Av)

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.curtis.curtisblog: info
  file: log/blog-pro.log

server:
  port: 8081